graviton.proxy.static.proxy.canonicalIdSchema:
    path: /schema/3rdparty/{api}/item
    defaults:
        _controller: graviton.proxy.controller.proxy:schemaAction
    requirements:
        api: '.+'

graviton.proxy.static.proxy.all:
    path: /3rdparty/{api}
    defaults:
        _controller: graviton.proxy.controller.proxy:proxyAction
    requirements:
        api: '.+'
